### PR TITLE
Update to AWS SDK v3

### PR DESCRIPTION
**Pull request by bfaulk96**
- Use AWS SDK 3
- Update .gitignore

### CODE REVIEW

**Comment by bfaulk96** [comment]
@abdullahshahin @andymjames @rhussmann are any of you available to approve/merge this?

**Comment by rhussmann** [comment]
@bfaulk96 just wanted to let you know I've seen this, and you're not shouting into the void ;o)

I personally haven't made any changes to this repository for many years, and honestly haven't done much with node since. I believe @abdullahshahin has merge powers. Calling out that you have marked this as a semver major version increment, as this does appear to be an API-level change.

**Comment by abdullahshahin** [comment]
Hello Gentlemen, apologies for the delayed response, I will have a look at it today or tomorrow max

**Comment by bfaulk96** [comment]
No worries! Haha just thought I'd contribute here specifically since it's the last of the libraries still requiring the massing `aws-sdk` in our stack, meaning massive builds 😛

Thanks for taking a look!

**Review by abdullahshahin — APPROVED** [review]
Looks good to me, thanks for contributing.

**Comment by rhussmann** [comment]
@bfaulk96 glad to see this went through. Since you appear to be using this in production, I'm sure any issues / patches you encounter in your use would be appreciated!

Good luck!

**Comment by bfaulk96** [comment]
One day in production so far, and everything is working still as it did before. 😊

Will certainly contribute if I notice anything!

**Pull request merged**
